baseURL = 'https://lihuanshuai.github.io/'
languageCode = 'zh-cn'
title = "Li Huanshuai's Blogs"

# Theme
theme = ['paper']

[params]
github = 'lihuanshuai'
rss = true
tags = true

avatar = 'https://avatars.githubusercontent.com/u/4586647'
name = 'Li Huanshuai'
bio = """Explore expansively, extract prudently, and express concisely."""
